# Generated by Django 6.0.7 on 2026-07-14 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('population_estimee', models.PositiveIntegerField(blank=True, null=True, verbose_name='Population estimée')),
            ],
            options={
                'verbose_name': 'Commune',
                'verbose_name_plural': 'Communes',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_proprietaire', models.CharField(choices=[('PHYSIQUE', 'Personne physique'), ('MORALE', 'Personne morale')], default='PHYSIQUE', max_length=10, verbose_name='Type')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet / Raison sociale')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('nin_ou_rccm', models.CharField(blank=True, help_text="Numéro d'identification nationale ou registre de commerce", max_length=50, verbose_name='NIN / RCCM')),
            ],
            options={
                'verbose_name': 'Propriétaire',
                'verbose_name_plural': 'Propriétaires',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Ex : TH-2024-00147', max_length=30, unique=True, verbose_name='Référence cadastrale')),
                ('quartier', models.CharField(blank=True, max_length=120)),
                ('superficie_m2', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie (m²)')),
                ('valeur_venale_fcfa', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valeur vénale estimée (FCFA)')),
                ('usage', models.CharField(choices=[('RESIDENTIEL', 'Résidentiel'), ('COMMERCIAL', 'Commercial'), ('AGRICOLE', 'Agricole'), ('INDUSTRIEL', 'Industriel'), ('MIXTE', 'Mixte')], default='RESIDENTIEL', max_length=20)),
                ('statut', models.CharField(choices=[('IMMATRICULEE', 'Immatriculée'), ('EN_COURS', "En cours d'immatriculation"), ('LITIGE', 'En litige'), ('NON_IMMATRICULEE', 'Non immatriculée')], default='NON_IMMATRICULEE', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelles', to='cadastre.commune')),
                ('proprietaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelles', to='cadastre.proprietaire')),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['-date_creation'],
            },
        ),
    ]
