# Generated by Django 6.0.8 on 2026-08-31 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointBornage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(help_text='Position du point dans le contour (1, 2, 3…), à la suite les uns des autres.', verbose_name='Ordre')),
                ('label', models.CharField(blank=True, help_text='Ex : B1, B2… (laisser vide pour un numérotage automatique)', max_length=10, verbose_name='Repère de la borne')),
                ('x', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='X (m)')),
                ('y', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Y (m)')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_bornage', to='cadastre.parcelle')),
            ],
            options={
                'verbose_name': 'Point de bornage',
                'verbose_name_plural': 'Points de bornage',
                'ordering': ['parcelle', 'ordre'],
                'constraints': [models.UniqueConstraint(fields=('parcelle', 'ordre'), name='unique_ordre_par_parcelle')],
            },
        ),
    ]
