# Generated by Django 6.0.8 on 2026-09-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0002_pointbornage'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='contour_carte',
            field=models.JSONField(blank=True, help_text="Liste de points [latitude, longitude] du contour extérieur réel de la parcelle, en coordonnées géographiques (WGS84), utilisée pour dessiner un vrai polygone sur la carte interactive plutôt qu'un simple point. Renseigné uniquement pour les parcelles importées depuis une géométrie réelle (voir la commande importer_bd_zone_nguinth) ; laisser vide pour les parcelles fictives, qui restent affichées par un point.", null=True, verbose_name='Contour réel (WGS84) pour la carte interactive'),
        ),
    ]
