# Generated by Django 6.0.8 on 2026-09-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastre', '0003_parcelle_contour_carte'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraitPlanGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_generation', models.DateTimeField(auto_now_add=True, verbose_name='Date de génération')),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraits_generes', to='cadastre.parcelle')),
            ],
            options={
                'verbose_name': 'Extrait de plan généré',
                'verbose_name_plural': 'Extraits de plan générés',
                'ordering': ['-date_generation'],
            },
        ),
    ]
