# Generated by Django 6.1.1 on 2026-09-02 19:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastre', '0002_pointbornage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_suivi', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Référence de suivi')),
                ('type_dossier', models.CharField(choices=[('IMMATRICULATION', "Demande d'immatriculation"), ('RECLAMATION', 'Réclamation')], max_length=20, verbose_name='Type de dossier')),
                ('localisation_saisie', models.CharField(blank=True, help_text="Ex. commune et quartier — utile pour une demande d'immatriculation d'une parcelle qui n'existe pas encore dans le système.", max_length=255, verbose_name='Localisation (si parcelle non encore enregistrée)')),
                ('nom_demandeur', models.CharField(max_length=150, verbose_name='Nom complet du demandeur')),
                ('telephone_demandeur', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email_demandeur', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('description', models.TextField(verbose_name='Description de la demande ou de la réclamation')),
                ('statut', models.CharField(choices=[('DEPOSE', 'Déposé'), ('EN_COURS', "En cours d'instruction"), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='DEPOSE', max_length=20)),
                ('commentaire_agent', models.TextField(blank=True, verbose_name="Commentaire de l'agent (visible par le demandeur lors du suivi)")),
                ('date_depot', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('agent_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_traites', to=settings.AUTH_USER_MODEL, verbose_name='Agent traitant')),
                ('parcelle', models.ForeignKey(blank=True, help_text='À renseigner si la parcelle est déjà enregistrée (ex. pour une réclamation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='cadastre.parcelle', verbose_name='Parcelle concernée')),
            ],
            options={
                'verbose_name': 'Dossier',
                'verbose_name_plural': 'Dossiers',
                'ordering': ['-date_depot'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='dossiers/%Y/%m/', verbose_name='Fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('dossier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='demarches.dossier')),
            ],
            options={
                'verbose_name': 'Pièce jointe',
                'verbose_name_plural': 'Pièces jointes',
            },
        ),
    ]
