# Generated by Django 6.0.8 on 2026-09-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demarches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossier',
            name='type_dossier',
            field=models.CharField(choices=[('Cadastre', [('IMMATRICULATION', "Immatriculation d'une parcelle"), ('PLAN_SITUATION', 'Plan de situation'), ('EXTRAIT_CADASTRAL', 'Extrait cadastral'), ('RENSEIGNEMENT_PARCELLE', 'Renseignements sur une parcelle'), ('BORNAGE', 'Bornage'), ('MORCELLEMENT', 'Morcellement'), ('FUSION', 'Fusion'), ('MISE_A_JOUR_CADASTRALE', 'Mise à jour cadastrale')]), ('Fiscalité', [('SITUATION_FISCALE', 'Situation fiscale'), ('ATTESTATION_FISCALE', 'Attestation fiscale'), ('PAIEMENT_QUITTANCE', 'Paiement / quittance'), ('REGULARISATION_FISCALE', 'Régularisation fiscale'), ('RECLAMATION_FISCALE', 'Réclamation'), ('CONSULTATION_IMPOTS_DUS', 'Consultation des impôts dus')])], max_length=30, verbose_name='Type de dossier'),
        ),
    ]
