# Generated by Django 6.0.8 on 2026-09-17 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demarches', '0003_remapper_reclamation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_suivi', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Référence de suivi')),
                ('motif', models.CharField(choices=[('BORNAGE', 'Bornage sur le terrain'), ('RETRAIT_DOCUMENT', "Retrait d'un document"), ('CONTESTATION', 'Contestation ou réclamation'), ('CONSEIL', 'Conseil sur une démarche'), ('AUTRE', 'Autre motif')], max_length=20)),
                ('precision', models.CharField(blank=True, help_text='Ex. référence de la parcelle ou du dossier concerné.', max_length=255, verbose_name='Précision (facultatif)')),
                ('date_souhaitee', models.DateField(verbose_name='Date souhaitée')),
                ('creneau', models.CharField(choices=[('MATIN', 'Matin (8h00 – 13h30)'), ('APRES_MIDI', 'Après-midi (14h30 – 17h00)')], max_length=15)),
                ('nom_demandeur', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('telephone_demandeur', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email_demandeur', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('statut', models.CharField(choices=[('DEMANDE', 'Demandé'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('HONORE', 'Honoré')], default='DEMANDE', max_length=15)),
                ('commentaire_agent', models.TextField(blank=True, verbose_name="Commentaire de l'agent (visible par le demandeur lors du suivi)")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de la demande')),
                ('date_maj', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('agent_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendez_vous_traites', to=settings.AUTH_USER_MODEL, verbose_name='Agent traitant')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_souhaitee', 'creneau'],
            },
        ),
    ]
