# Generated by Django 6.1 on 2026-09-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_actualite_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='source_url',
            field=models.URLField(blank=True, help_text="Ex. lien vers l'article original sur dgid.sn, pour permettre au lecteur de vérifier l'information.", max_length=300, verbose_name='Lien vers la source officielle'),
        ),
    ]
