# Generated by Django 6.1.1 on 2026-09-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_actualites_dgid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField(help_text="Texte de la section. Les sauts de ligne sont conservés à l'affichage.")),
                ('ordre', models.PositiveIntegerField(default=0, help_text='Les sections sont affichées de la plus petite à la plus grande valeur.', verbose_name="Ordre d'affichage")),
                ('publie', models.BooleanField(default=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Section du guide',
                'verbose_name_plural': 'Sections du guide',
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
