# Generated by Django 6.0.8 on 2026-09-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_enrichir_section_nicad'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionguide',
            name='categorie',
            field=models.CharField(choices=[('COMPRENDRE', 'Comprendre le cadastre'), ('IMMATRICULER', 'Immatriculer une parcelle'), ('FISCALITE', 'Fiscalité foncière'), ('PRATIQUE', 'Pratique')], default='COMPRENDRE', help_text='Thème sous lequel la section est regroupée sur la page publique du guide.', max_length=20, verbose_name='Rubrique'),
        ),
    ]
