# Generated by Django 6.0.8 on 2026-09-21 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_corriger_texte_extrait_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Action')),
                ('details', models.TextField(blank=True, verbose_name='Détails')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journal', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
            ],
            options={
                'verbose_name': "Entrée du journal d'activité",
                'verbose_name_plural': "Journal d'activité",
                'ordering': ['-date_action'],
            },
        ),
    ]
