# Generated by Django 6.0.7 on 2026-07-14 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxeFonciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveIntegerField(default=2026)),
                ('taux_applique', models.DecimalField(decimal_places=4, max_digits=5)),
                ('montant_du', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant dû (FCFA)')),
                ('date_emission', models.DateField(auto_now_add=True)),
                ('date_limite', models.DateField()),
                ('statut', models.CharField(choices=[('EMISE', 'Émise'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée'), ('EN_RETARD', 'En retard')], default='EMISE', max_length=25)),
                ('parcelle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taxes', to='cadastre.parcelle')),
            ],
            options={
                'verbose_name': 'Taxe foncière',
                'verbose_name_plural': 'Taxes foncières',
                'ordering': ['-annee', '-date_emission'],
                'unique_together': {('parcelle', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('date_paiement', models.DateField(auto_now_add=True)),
                ('reference_transaction', models.CharField(blank=True, max_length=60)),
                ('taxe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='fiscalite.taxefonciere')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
